ALTER TABLE customer ADD COLUMN balance DECIMAL(20, 8) DEFAULT 0;
ALTER TABLE customer ADD COLUMN auto_renew BOOLEAN DEFAULT FALSE;
ALTER TABLE customer ADD COLUMN auto_renew_duration INTEGER DEFAULT 30;
