FROM scratch

LABEL org.opencontainers.image.description="Remnawave Telegram Shop Bot (Prebuilt)"

# Certificates and Timezone
COPY --from=alpine:latest /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Artifacts
COPY app /app/app
COPY db /db
COPY translations /translations
COPY web-app-dist /web-app/dist

USER 1000
ENV DISABLE_ENV_FILE=true

CMD ["/app/app"]
